name: Integrations

# on: [push, pull_request]
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Copy docker/.env.template as .env
        uses: cp external/ckan/contrib/docker/.env.template external/ckan/contrib/docker/.env

      - name: Build images
        run: docker compose -f external/ckan/contrib/docker/docker-compose.yml -f docker-compose.yml up --build -d
        working-directory: ./development

