name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Install Python 3.8.16
        uses: actions/setup-python@v4
        with:
            python-version: "3.8.16"

      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: check out ckan version 2.9.7
        run: git submodule update --init --recursive
        working-directory: ./development

      - name: Copy .env.template as .env
        run: |
          cp external/ckan/contrib/docker/.env.template external/ckan/contrib/docker/.env
          sed -i -e 's/zope.interface==4.3.2/zope.interface==5.0.0/' external/ckan/requirements.txt
        working-directory: ./development

      - name: Build images
        run: docker compose -f external/ckan/contrib/docker/docker-compose.yml -f docker-compose.yml up --build -d
        working-directory: ./development

      - name: install ckanext-feedback
        run: |
          docker exec ckan /usr/local/bin/ckan -c /etc/ckan/production.ini datastore set-permissions | docker exec -i db psql -U ckan
          docker exec -i ckan bash -c ". /usr/lib/ckan/venv/bin/activate && pip install /opt/ckanext-feedback"

      - name: install requirement
        run: |
          docker exec -i ckan bash -c ". /usr/lib/ckan/venv/bin/activate &&
          pip install -r /usr/lib/ckan/venv/src/ckan/dev-requirements.txt &&
          pip install pytest-ckan &&
          createdb ckan_test -O ckan -E utf-8 -h db -U ckan &&
          ckan -c /usr/lib/ckan/venv/lib/python3.8/site-packages/ckanext/feedback/tests/config/test.ini db init"

      - name: test
        run: |
          docker exec -i ckan bash -c ". /usr/lib/ckan/venv/bin/activate && 
          pip install /opt/ckanext-feedback && 
          CKAN_SQLALCHEMY_URL= CKAN_DATASTORE_READ_URL= CKAN_DATASTORE_WRITE_URL= pytest --ckan-ini=/usr/lib/ckan/venv/lib/python3.8/site-packages/ckanext/feedback/tests/config/test.ini --cov=ckanext.feedback --cov-branch --disable-warnings --cov-report=term-missing /usr/lib/ckan/venv/lib/python3.8/site-packages/ckanext/feedback/tests"