name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Install Python 3.8.16
        uses: actions/setup-python@v4
        with:
            python-version: "3.8.16"

      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: check out ckan version 2.9.7
        run: git submodule update --init --recursive
        working-directory: ./development

      - name: Copy .env.template as .env
        run: |
          cp external/ckan/contrib/docker/.env.template external/ckan/contrib/docker/.env
          sed -i -e 's/zope.interface==4.3.2/zope.interface==5.0.0/' external/ckan/requirements.txt
        working-directory: ./development

      - name: Build images
        run: |
          docker compose -f external/ckan/contrib/docker/docker-compose.yml -f docker-compose.yml up --build -d
        working-directory: ./development

      - name: db settings
        run: |
          docker exec -i ckan bash -c "./usr/lib/ckan/venv/bin/activate && pip install /opt/ckanext-feedback"