name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      # The CKAN version tag of the Solr and Postgres containers should match
      # the one of the container the tests run on.
      # You can switch this base image with a custom image tailored to your project
      image: openknowledge/ckan-dev:2.9
    services:
      solr:
        image: ckan/ckan-solr-dev:2.9
      postgres:
        image: ckan/ckan-postgres-dev:2.9
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
          image: redis:3

    env:
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@postgres/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@postgres/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@postgres/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1

    steps:
    - name: Check out Repository
      uses: actions/checkout@v3

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install requirements
      # Install any extra requirements your extension has here (dev requirements, other extensions etc)
      run: |
        poetry install --with dev
        sed -i -e 's/use = config:.*/use = config:\/srv\/app\/src\/ckan\/test-core.ini/' ckanext/feedback/tests/config/test.ini
    - name: Setup extension
      # Extra initialization steps
      run: |
        pip install -r /usr/lib/ckan/venv/src/ckan/dev-requirements.txt
        pip install pytest-ckan
        createdb ckan_test -O ckan -E utf-8 -h db -U ckan
        ckan -c /usr/lib/ckan/venv/lib/python3.8/site-packages/ckanext/feedback/tests/config/test.ini db init"
#        ckan -c ckanext/feedback/tests/config/test.ini db init

      # permission denied from ckan container if install python3.8.16 .

    - name: Run tests
      run: | 
        /github/home/.local/bin/poetry run pytest --ckan-ini=ckanext/feedback/tests/config/test.ini --cov=ckanext.feedback --disable-warnings ckanext/feedback

    # necessary to modify "Setup extension" and "Run tests" at the CI setting phaze
